pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- task: PipAuthenticate@0
  inputs:
    artifactFeeds: wb-artifacts

- script: make init

- script: make test

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'